from transformers import pipeline

# Load Hugging Face sentiment pipeline
sentiment_pipeline = pipeline("sentiment-analysis")

# Headlines list (shortened here for readability, paste your full list in practice)
headlines = [
"1. Three dead after historic funicular railway derails in Lisbon"
"2. US strike on 'Venezuela drug boat': What do we know, and was it legal?"
"3. Three dead after historic funicular railway derails in Lisbon"
"4. US strike on 'Venezuela drug boat': What do we know, and was it legal?"
"5. Hot mic catches Xi and Putin discussing organ transplants and immortality"
"6. Epstein accusers speak outside US Capitol"
"7. 'Ketamine Queen' pleads guilty in Matthew Perry overdose case"
"8. Captain Scott’s famous polar shipwreck as never seen before"
"9. Putin says Russia will achieve all aims militarily if Ukraine does not agree deal"
"10. Only from the BBC"
"11. The British isle with its own language"
"12. Why some cultures welcome 'hearing voices'"
"13. Riviera or statehood: the future of Gaza"
"14. More news"
"15. China's Xi steals the limelight in a defiant push against US-led world order"
"16. US Open: Follow singles quarter-finals"
"17. Australia-Israel relations have hit a low point. Behind the scenes, it's business as usual"
"18. 'We know their names': Epstein victims say they are making their own list"
"19. Israel intensifies Gaza City attacks as UN warns of 'horrific' consequences for displaced families"
"20. US Open: Follow singles quarter-finals"
"21. What the new weapons on show say about China's military strength"
"22. Hundreds of women with brooms join protests as Indonesia leader flies to China"
"23. Australia-Israel relations have hit a low point. Behind the scenes, it's business as usual"
"24. Must watch"
"25. Xi and Putin discuss organ transplants and living 'indefinitely'"
"26. Nigel Farage and US congressman clash on freedom of speech"
"27. Fountains of lava shoot into the air as Kilauea erupts"
"28. Key moments from China's military parade"
"29. Moment Xi, Putin and Kim pose with world leaders at China's military parade"
"30. Wildfire ravages historic California gold rush town destroying homes"
"31. New ICBM missile on display at China's military parade"
"32. The majestic ancient ruins of Cleopatra's Bath"
"33. Tennis"
"34. Electric New York energy reignites etiquette debate"
"35. Venice Film Festival"
"36. US nuclear attack thriller is 'more terrifying than most horror films' ★★★★☆"
"37. The Rock is Oscar-worthy in his new film ★★★★☆"
"38. The new film about how Putin's Russia was born"
"39. Culture"
"40. The Office spin-off The Paper is a 'winning' show ★★★★★"
"41. US & Canada news"
"42. Florida aims to ban vaccine mandates for schoolchildren"
"43. Newsmax sues Fox News in battle of right-wing TV networks"
"44. Bank of England 'very concerned' at Trump threats to US Fed"
"45. US House panel releases 33,000 pages of Epstein files"
"46. More world news"
"47. Search for painting looted by Nazis may have found more stolen art"
"48. Charges against Brazil's Bolsonaro are political, says lawyer"
"49. Sudan landslide: A collapsing mountain and bodies still buried under rubble"
"50. Deadly South African building fire blamed on lack of affordable housing"
"51. Business"
"52. Luigi Mangione's likeness used to model shirt on Shein"
"53. US revokes TSMC's authorisation on China-bound tech"
"54. Family of dead teen say ChatGPT's new parental controls not enough"
"55. A let-off or tougher than it looks? What the Google monopoly ruling means"
"56. Sport"
"57. The art of the free transfer - and why Real Madrid are masters of it"
"58. Who will win Super Bowl & be MVP? NFL pundits' predictions"
"59. IndyCar's Herta appointed Cadillac test driver"
"60. Cummins to take rehab 'risks' to be fit for Ashes"
"61. Latest Sport audio"
"62. Football Daily"
"63. 72+: The EFL Podcast"
"64. Rugby Union Weekly"
"65. Barely Rugby: Van life, dogs & colouring by numbers"
"66. Football Daily"
"67. Destination New Jersey: Club World Cup reflections, Ecuador & Canadian Soccer"
"68. Football Daily"
"69. Women's Football Weekly: The WSL returns!"
"70. Football Daily"
"71. Monday Night Club: Transfer Deadline Day"
"72. The Wayne Rooney Show"
"73. Arsenal’s Lack Of Bravery & Pep’s Last Dance?"
"74. Football Daily"
"75. Premier League Review with Rick Edwards"
"76. 606"
"77. Brighton rock Manchester City, and Szoboszlai strike sinks Arsenal at Anfield…"
"78. Tech"
"79. M&S hackers claim to be behind Jaguar Land Rover cyber attack"
"80. UK government unable to calculate Afghan data breach cost, watchdog says"
"81. Google avoids break-up but must share data with rivals"
"82. Jaguar Land Rover production severely hit by cyber-attack"
"83. Science & health"
"84. Energy drinks to be banned for under-16s in England"
"85. RFK Jr 'endangering' Americans, say former CDC bosses"
"86. Are you eating the right amount of salt?"
"87. Gene tests begin in women's athletics - new rule explained"
"88. Culture"
"89. 14 of the best films to watch this September"
"90. Radiohead to tour for first time in seven years"
"91. Seven claims made in new royal book from Brexit to Coronation"
"92. Sting sued by ex-Police bandmates over royalties"
"93. Arts"
"94. 'How I discovered a masterpiece'"
"95. The secret lives of Yakuza women"
"96. Is this the first time sex was depicted in art?"
"97. The moment that changed Picasso"
"98. Watch"
"99. The sunken secrets of Roman pleasure palaces"
"100. Travel"
"101. The eerie beauty of Estonia's silent swamps"
"102. The remote village drawing stargazers from around the world"
"103. The 'trash district' fuelling Mexico City's top restaurants"
"104. Where American travellers are spending Labor Day weekend"
"105. World's Table"
"106. Is 'pay what you can' the newest restaurant trend?"
"107. The little-known isle where meals cook beneath your feet"
"108. Costa Rica's nine-course meal in the sky"
"109. What is 'real' Italian pizza?"
"110. Earth"
"111. Why plastic-filled balls are washing up on beaches"
"112. Floods kill 30 and submerge 1,400 villages in Indian state"
"113. Compassion v fear: Delhi divided over feeding stray dogs"
"114. Timelapse shows Northern Lights display over North Sea"
"115. Video"
"116. How tech is helping the world’s most endangered species"
"117. The secret childhood of Princess Diana"
"118. The most venomous snake of Guyana’s Amazon rainforest"
"119. Watch the face-clawing sloth bear that scares tigers"
"120. Discover more from the BBC"
"121. In History"
"122. Download the BBC app"
"123. Health Fix"
"124. Register for a BBC account"
"125. Sign up for the Essential List"
"126. Sign up to News Briefing"

]

# Run sentiment analysis in batch
results = sentiment_pipeline(headlines)

# Print each headline with sentiment result
for h, r in zip(headlines, results):
    print(f"Headline: {h}")
    print(f" → Sentiment: {r['label']} (confidence: {r['score']:.2f})\n")
